# Visit https://github.com/lowlighter/metrics/blob/master/action.yml for full reference
name: Metrics
on:
  # Schedule updates (each hour)
  schedule: [{cron: "0 * * * *"}]
  # Lines below let you run workflow manually and on each commit
  workflow_dispatch:
  push: {branches: ["master", "main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          # Your GitHub token
          token: ${{ secrets.METRICS_TOKEN }}
          # Committer token
          committer_token: ${{ secrets.GH_TOKEN }}
          # Options
          user: Queiroz-Dv
          template: classic
          base: header, metadata
          config_timezone: America/Sao_Paulo
          plugin_achievements: yes
          plugin_achievements_display: compact
          plugin_achievements_secrets: yes
          plugin_achievements_threshold: E
          plugin_followup: no
          plugin_introduction: no
          plugin_introduction_title: no
          plugin_languages: no
          plugin_languages_categories: programming
          plugin_languages_colors: github
          plugin_languages_limit: 15
          plugin_languages_recent_categories: programming
          plugin_languages_recent_days: 14
          plugin_languages_recent_load: 300
          plugin_languages_sections: most-used
          plugin_languages_threshold: 0%
          plugin_lines: no
          plugin_notable: no
          plugin_pagespeed: no
          plugin_pagespeed_url: .user.website
          plugin_people: no
          plugin_people_limit: 24
          plugin_people_size: 28
          plugin_people_types: followers, following
          plugin_projects: no
          plugin_projects_limit: 4
          plugin_stars: no
          plugin_stars_limit: 4
          plugin_habits: yes
          plugin_habits_facts: yes
          plugin_habits_charts: no
          plugin_habits_trim: no
          plugin_wakatime: no
          plugin_wakatime_sections: time, projects, projects-graphs, languages, languages-graphs, editors, os
          plugin_wakatime_token: ${{ secrets.WAKATIME_API_KEY }}
