name: Waka Readme

on:
  workflow_dispatch:
  schedule:
    - cron: '0 * * *'

jobs:
  update-readme:
    name: Update Readme with Metrics
    runs-on: ubuntu-latest
    steps:
      - uses: anmol098/waka-readme-stats@master
        with:
          WAKATIME_API_KEY: ${{ secrets.d2f372c8-04bf-4271-8ff8-e4dc5ed48274 }}
          GH_TOKEN: ${{ secrets.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 }}
          SHOW_LOC_CHART: "False"
          SHOW_LANGUAGE_PER_REPO: "False"
          SHOW_PROFILE_VIEWS: "False"
          SHOW_SHORT_INFO: "False"
          SHOW_LANGUAGE: "False"
          SHOW_PROJECTS: "False"
